name: CI for JS Testing with Linting

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]

    steps:
    - uses: actions/checkout@v3

    - name: Show current directory and files
      run: |
        pwd
        ls -la

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npx eslint .

    - name: Run tests
      run: npx jest