name: CI for JS Testing with Linting

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci
      working-directory: ${{ github.workspace }}

    - name: Run ESLint
      run: npx eslint .
      working-directory: ${{ github.workspace }}

    - name: Fix jest permissions
      run: chmod +x node_modules/.bin/jest
      working-directory: ${{ github.workspace }}

    - name: Run tests
      run: npx jest
      working-directory: ${{ github.workspace }}
