name: CI for JS Testing

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Show jest binary permissions
      run: ls -la node_modules/.bin/

    - name: Run tests
      run: npx jest
      
# тут я хочу залишити коментар